name: Test Action
on:
    push:
      branches:
        - main
        - master
    pull_request:
      branches:
        - main
        - master
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name : Check out Repository
          uses: actions/checkout@v3

        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Build Docker Image
          run: docker build -t njk7740/app:latest .

        - name: Docker Hub Login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Docker Image
          run: docker push njk7740/app:latest

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASSWORD }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/app
              if docker ps | grep -q app1; then
              docker run --name app2 -d -p 8081:8080 --rm ${{ secrets.DOCKER_USERNAME }}/app
              while true; do
              if docker logs app2 | grep -q "Started TeamApplication"; then
              break
              fi
              sleep 1
              done
              docker exec nginx sed -i 's/8080/8081/' /etc/nginx/conf.d/default.conf
              docker exec nginx service nginx reload
              docker stop app1
              while docker inspect app1 &> /dev/null; do
              sleep 1
              done
              elif docker ps | grep -q app2; then
              docker run --name app1 -d -p 8080:8080 --rm ${{ secrets.DOCKER_USERNAME }}/app
              while true; do
              if docker logs app1 | grep -q "Started TeamApplication"; then
              break
              fi
              sleep 1
              done
              docker exec nginx sed -i 's/8081/8080/' /etc/nginx/conf.d/default.conf
              docker exec nginx service nginx reload
              docker stop app2
              while docker inspect app2 &> /dev/null; do
              sleep 1
              done
              fi
              docker rmi $(docker images -f "dangling=true" -q)